name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          user: Tal0na
          token: ${{ secrets.GH_PAT }}
